### ISSUE TITLE
enlaces PhET rotos

### ISSUE THREAD

**Issue by jgpATs2w** [GRUPOANAYA/laboratorios-publico#1]
Las urls no pueden tener espacios ni tildes. Por eso hay algunos enlaces que muestran correctamente

**Comment by crismcas** [comment]
Ya lo sé... Son los nombres con los que se descargaron del propio PhET, que dijimos de dejarlos tal cual y no los edité. Como ahora no puedo entrar el GRC desde casa, tengo pendiente arreglarlo cuando pueda hacerlo.
